version: '3'
services:
  database:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3307:3307
    environment:
     - MYSQL_ROOT_PASSWORD=pass
     - MYSQL_DATABASE=achatdb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=pass

  spring-boot:
    image: badiskhalsi/springproject
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - AppNet
    restart: on-failure
  angular:
    image: badiskhalsi/angularproject
    container_name: angular
    ports:
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - AppNet

networks:
  AppNet:
